use_frameworks!

target "RobotoFontLoaderExample" do
  pod 'MDFRobotoFontLoader', :path => '../../../'
  pod 'MDFRobotoFontLoader/MDCTypographyAdditions', :path => '../../../'
  pod 'CatalogByConvention'

  target 'RobotoFontLoaderExampleTests' do
  end
end
