use_frameworks!

target "RobotoFontLoaderExample" do
  pod 'MDFRobotoFontLoader', :path => '../../../'
  pod 'CatalogByConvention'

  # Note: this works around the unreleased state of the MDCTypography.
  pod 'MaterialComponents/Typography', :path => '../../../../material-components-ios/'

  target 'RobotoFontLoaderExampleTests' do
  end
end
